### ISSUE TITLE
Planetary protection warning will be posted repeatedly

### ISSUE THREAD

**Issue by OliverCole** [botwillacceptanything/botwillacceptanything#116]
The warning message added in #92 will be posted repeatedly until the PR is closed. In fact, any other messages implemented in the same way will be as well. As I have some ideas for other messages, we should fix this first.

If you could leave this a few days, I'd like to address this myself to get myself warmed up on the code :)

**Comment by aristidb** [comment]
This can be closed since #119 has been merged, right?

**Comment by avdg** [comment]
:+1:

**Comment by avdg** [comment]
(just trying something I know it will fail :-))
