### ISSUE TITLE
We need more users!

### ISSUE THREAD

**Issue by mappum** [botwillacceptanything/botwillacceptanything#123]
Now that the traffic from Hacker News has died down, we need a new source of users. Any ideas?

**Comment by avdg** [comment]
Add drama

**Comment by thenightwassave** [comment]
We need bot outreach!

**Comment by lukeheath** [comment]
Reddit?

**Comment by avdg** [comment]
https://www.reddit.com/r/programming/comments/325arp/bot_will_accept_anything_a_bot_that_accepts/ got deleted though...

**Comment by mappum** [comment]
@avdg I deleted that since it was being downvoted.

**Comment by AlphaT3ch** [comment]
I tried sprouting some traffic [here](http://lmlair.ddns.net/thread/518-self-accepting-github-pull-request-bot-thing/), but nobody seemed to care... :/

**Comment by avdg** [comment]
@mappum I got downvoted all the time on reddit

**Comment by avdg** [comment]
at least on the busy places

**Comment by avdg** [comment]
@AlphaT3ch Not Japanese enough I guess

**Comment by SamsPepper1** [comment]
I've been thinking about this a bit. I think that the bot should be able to do its own outreach. I'm going to start by seeing what we can do with some of the nlp libraries available, and maybe make the Twitter account more personable

**Comment by SpenserJ** [comment]
Haha I was think about the same thing last night. I don't want the not to turn into a spammer on twitter, but reaching out to people with a similar interest could be neat

**Comment by uptownhr** [comment]
close? why are non of these issues being closed.

**Comment by avdg** [comment]
There's no goal, isn't there?
