### ISSUE TITLE
Remove twitter code from voting.js

### ISSUE THREAD

**Issue by thenightwassave** [botwillacceptanything/botwillacceptanything#130]
I think voting.js should stay pure and just publish an event that we can listen for elsewhere and then we can hook into it to do stuff like update twitter, etc.

**Comment by SpenserJ** [comment]
There is a new event system that has been added in #128, that we could listen to for the events from GitHub, and we could fire off some of our own when voting.js begins to merge or close.

**Comment by korczis** [comment]
I agree with @thenightwassave

**Comment by thenightwassave** [comment]
Now the IRC communication code is also polluting voting.js too

**Comment by SpenserJ** [comment]
Twitter and IRC have been removed from voting.js now.

**Comment by botwillacceptanything** [comment]
Closing as this is resolve now.
