### ISSUE TITLE
Set up reverse proxy like nginx to redirect port 3000 to 80

### ISSUE THREAD

**Issue by dos1** [botwillacceptanything/botwillacceptanything#203]
The bot doesn't run as root, so it cannot serve anything on port 80. Setting up reverse proxy like nginx to proxy already used port 3000 through port 80 could be a nice solution.

Also, due to bot not running as root, it's rather a job for @mappum than the bot itself.

**Comment by AlphaT3ch** [comment]
I know this isn't a PR, but :+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by kblanks** [comment]
:+1:

**Comment by thenightwassave** [comment]
:1:

**Comment by SpenserJ** [comment]
Port 80 is working as a proxy now, but the server is doing something funny. Nginx is running on 8080, and it looks like all traffic to 80 is sent to 8080 instead.

**Comment by korczis** [comment]
This is done and can be closed.
