### ISSUE TITLE
Site is down?

### ISSUE THREAD

**Issue by jaredly** [botwillacceptanything/botwillacceptanything#218]
It just merged a PR, and the site is now not responding... http://botwillacceptanything.com:3000/

although maybe it just takes a while to restart?

**Comment by avdg** [comment]
Join irc for updates http://kiwiirc.com/client/irc.freenode.net/botwillacceptanything

**Comment by avdg** [comment]
Bot is down, @mappum is trying to fix

**Comment by samis** [comment]
Bot is currently down. There has been work to bring it back up.

**Comment by dos1** [comment]
Up again!

**Comment by dos1** [comment]
Please close old issues.

**Comment by botwillacceptanything** [comment]
Manually closing on behalf of myself.
