### ISSUE TITLE
[TODO] Add unicorns

### ISSUE THREAD

**Issue by avdg** [botwillacceptanything/botwillacceptanything#240]
![Ponies](https://i.imgur.com/bZg5ldp.jpg) ![More ponies](https://i.imgur.com/evlGRRw.png)

(urls from @AlphaT3ch )

**Comment by AlphaT3ch** [comment]
Dwis unicown is de bestest 1 ive eva seeen! http://fc08.deviantart.net/fs71/i/2011/052/9/7/fat_unicorn_by_triumfa-d3a25c7.jpg

**Comment by samis** [comment]
Nice.

**Comment by LifeMushroom** [comment]
:D

**Comment by Prior99** [comment]
Attempt to fix in PR #324.

**Comment by dos1** [comment]
...but... but... Rainbow Dash is not a unicorn :c

**Comment by Prior99** [comment]
Maybe resolved in PR #327 ?

**Comment by dos1** [comment]
Twilight Sparkle would resolve it. We've only got Pinkie Pie and Rainbow Dash so far, and both of them aren't unicorns :(

**Comment by shalecraig** [comment]
bump

**Comment by avdg** [comment]
Closing this, but I hope no unicorns gets hurt by this. Feel free to create a new issue if you feel like it.
