### ISSUE TITLE
bot will check out newest version of its own code against will of bot's operator

### ISSUE THREAD

**Issue by dbpokorny** [botwillacceptanything/botwillacceptanything#299]
Not the first time a machine has done this.

(M-foo=b45d07) ~/github/botwillacceptanything$ git reset --hard 52def376cb5fa43d4d545c54a7e14aaa667032ff
HEAD is now at 52def37 Merge pull request #273 from dbpokorny/master
(M-foo=52def3) ~/github/botwillacceptanything$ git checkout -B master-foo
Reset branch 'master-foo'
(M-foo=52def3) ~/github/botwillacceptanything$ clear

(M-foo=52def3) ~/github/botwillacceptanything$ node main.js 
Initializing middleware.
Initializing integrations.
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/bodyParser.js
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/errorHandler.js
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/favicon.js
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/logger.js
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/publicViews.js
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/static.js
Initializing routes.
Loading /Users/dbp/github/botwillacceptanything/lib/integrations/irc.js
No IRC settings in config. IRC bot disabled.
Loading /Users/dbp/github/botwillacceptanything/lib/integrations/twitter.js
UNCAUGHT ERROR: Error: ENOENT, open '/Users/dbp/github/botwillacceptanything/tmp/access.log'
Error: ENOENT, open '/Users/dbp/github/botwillacceptanything/tmp/access.log'
Loading /Users/dbp/github/botwillacceptanything/lib/routes/commits.js
Loading /Users/dbp/github/botwillacceptanything/lib/routes/root.js
Loading /Users/dbp/github/botwillacceptanything/lib/routes/secrets.js
Loading /Users/dbp/github/botwillacceptanything/lib/routes/statistics.js
Loading /Users/dbp/github/botwillacceptanything/lib/routes/stdout.js
Loading /Users/dbp/github/botwillacceptanything/lib/routes/votes.js
Loading /Users/dbp/github/botwillacceptanything/lib/routes/webhook.js
(M-foo=b45d07) ~/github/botwillacceptanything$ ./authors.sh stderr: null ./authors.sh: line 3: /dev/tty: Device not configured

npm install stderr: npm
npm install stderr:  WARN prefer global jshint@2.6.3 should be installed with -g

Initializing middleware.
Initializing integrations.
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/bodyParser.js
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/errorHandler.js
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/favicon.js
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/logger.js
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/publicViews.js
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/static.js
Initializing routes.
Loading /Users/dbp/github/botwillacceptanything/lib/integrations/github_labels.js
Loading /Users/dbp/github/botwillacceptanything/lib/integrations/irc.js
No IRC settings in config. IRC bot disabled.
Loading /Users/dbp/github/botwillacceptanything/lib/integrations/twitter.js
UNCAUGHT ERROR: Error: ENOENT, open '/Users/dbp/github/botwillacceptanything/tmp/access.log'
Error: ENOENT, open '/Users/dbp/github/botwillacceptanything/tmp/access.log'
Loading /Users/dbp/github/botwillacceptanything/lib/routes/commits.js
Loading /Users/dbp/github/botwillacceptanything/lib/routes/root.js
Loading /Users/dbp/github/botwillacceptanything/lib/routes/secrets.js
Loading /Users/dbp/github/botwillacceptanything/lib/routes/statistics.js
Loading /Users/dbp/github/botwillacceptanything/lib/routes/stdout.js
Loading /Users/dbp/github/botwillacceptanything/lib/routes/votes.js
Loading /Users/dbp/github/botwillacceptanything/lib/routes/webhook.js
Bot is initialized. HEAD: b45d075eb189f3b992e624432ed2f61a3717a122

**Comment by SpenserJ** [comment]
Easy solution during development is to find the `repo.sync(cb);` line in `function sync(cb)`, and replace it with `cb();`

When we have environment configs, I'm going to add in a skip in that section.

**Comment by botwillacceptanything** [comment]
This is fixed with #356
