### ISSUE TITLE
Middleware loads VIM swap files

### ISSUE THREAD

**Issue by dbpokorny** [botwillacceptanything/botwillacceptanything#303]
Initializing middleware.
Initializing mocks.
Loading /Users/dbp/github/botwillacceptanything/tests/mocks/twitter.js
Initializing integrations.
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/bodyParser.js
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/errorHandler.js
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/favicon.js
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/logger.js
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/publicViews.js
Loading /Users/dbp/github/botwillacceptanything/lib/middleware/static.js
Initializing routes.
Loading /Users/dbp/github/botwillacceptanything/lib/integrations/github_labels.js
Loading /Users/dbp/github/botwillacceptanything/lib/integrations/irc.js
No IRC settings in config. IRC bot disabled.
Loading /Users/dbp/github/botwillacceptanything/lib/integrations/twitter.js
UNCAUGHT ERROR: Error: ENOENT, open '/Users/dbp/github/botwillacceptanything/tmp/access.log'
Error: ENOENT, open '/Users/dbp/github/botwillacceptanything/tmp/access.log'
Loading /Users/dbp/github/botwillacceptanything/lib/routes/.statistics.js.swp

/Users/dbp/github/botwillacceptanything/lib/routes/.statistics.js.swp:1
(function (exports, require, module, __filename, __dirname) { b0VIM 7.4
                                                                    ^^^
UNCAUGHT ERROR: SyntaxError: Unexpected number
SyntaxError: Unexpected number
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/dbp/github/botwillacceptanything/lib/routes/index.js:36:33
    at Object.oncomplete (fs.js:107:15)
Bot is initialized. HEAD: b45d075eb189f3b992e624432ed2f61a3717a122

**Comment by SpenserJ** [comment]
Nice to see another Vim user. I'm sure we can find a good fix for the swap files. I haven't run into this because I store my swaps in ~/.vimdata: https://github.com/SpenserJ/dotfiles/blob/master/home/.vim/rc/environment.vimrc#L1-L4
