### ISSUE TITLE
Integration with tip4commit

### ISSUE THREAD

**Issue by daedalus** [botwillacceptanything/botwillacceptanything#362]
Taking in count #67 and #47
 
It is no bad idea to register this project in https://tip4commit.com/ 
Tip for commit is a service where each registered project gets a porcentual wage in bitcoins depending on its commits.

Any coments?

**Comment by SpenserJ** [comment]
I think it would be interesting, and I'd even be willing to toss some money into the pot.

**Comment by SpenserJ** [comment]
This was added in #447, but when I set up my coinbase/coingiving account, I was unable to set myself up as a project supporter, and am unable to send btc to the project. Hopefully this is fixed soon, but Tip4Commit seems to be dying
