### ISSUE TITLE
Random whitespace on website

### ISSUE THREAD

**Issue by AlphaT3ch** [botwillacceptanything/botwillacceptanything#393]
There used to be an under construction sign in it, but not anymore :/ so I don't know...
[Picture Here](http://i.imgur.com/eAD8D6K.png)

**Comment by dos1** [comment]
It's still there, but as marquee element isn't really very loved by browsers it's implemented quite primitively - it waits for onload element to start animating, while something on the page seems to be blocking page load - notice the progress circle rotating indefinitely in Firefox.

Also
>Internet Explorer

**Comment by AlphaT3ch2** [comment]
@dos1: ah okay... I also hate IE too, but it's the only thing on my Windows RT tablet :/
