### ISSUE TITLE
IRC Channel Registration

### ISSUE THREAD

**Issue by SpenserJ** [botwillacceptanything/botwillacceptanything#423]
The Group Management/Registration System at Freenode hasn't been enabled since 2012, and it is impossible for us to regain operator or register the channel while everyone is joined. Since we can't kick everyone without operator, and the staff can't help us regain op, we have three options.

1. Accept our op-less functionality, and lose out on the ability to have the bot manage the channel.
1. Change to another channel, that we have registered before sharing the link. I've registered up #anythingbot if we want to use that.
1. Change to another server, that offers better group registration, which would grant the ability to give IP masks to our users.
1. Switch over to [Gitter](https://gitter.im/)
1. Switch over to [Slack](https://slack.com)

I'm preferential to migrating to a new channel, which brings the issue of moving everyone currently in the channel to the new channel. It seems like most clients auto-accept when invited to another channel, and we could go through and `/invite` everyone when we've decided on a new channel, as well as setting the topic to point to the new channel.

**Comment by dbpokorny** [comment]
:+1: option 4

**Comment by AlphaT3ch2** [comment]
Eh :-1: for option 4... Maybe we could go to anything bot and wait for everyone to leave #botwillacceptanything and then just have everyone rejoin once it's registered... We also shouldn't leave Freenode because it's the open-source IRC network. So yeah, I think #anythingbot can just be a temporary channel while we wait for everyone to leave the other one...

**Comment by shalecraig** [comment]
5. Slack?!?!?!

**Comment by SpenserJ** [comment]
I love the idea of slack. We use it at work, and it is phenomenal

**Comment by dequis** [comment]
Slack requires invites to join a channel (or really awkward scripts to auto-invite people).

Also personally I wouldn't bother connecting to the equivalent of a whole new irc network just for this channel.

**Comment by shalecraig** [comment]
We *could* get the bot to auto-invite people who create PRs, and make the slack channel public.

**Comment by dbpokorny** [comment]
@dequis I sent you an invite, did that work?

**Comment by SpenserJ** [comment]
@shalecraig Part of the reason for wanting to fix our channel registration is so that we can do things like setting the topic to display the number of votes in progress, and the latest feature. There is significantly more flexibility when we have the ability to manage the channel via op, than hoping everyone plays nice and leaving the topic open to the world to change.
