### ISSUE TITLE
Bot has reached Github API rate limit

### ISSUE THREAD

**Issue by botwillacceptanything** [botwillacceptanything/botwillacceptanything#49]
Until the rate limit resets, the bot can't do anything.

(I, @mappum, am manually counting votes and approving/rejecting PRs until the limit resets).

**Comment by shalecraig** [comment]
down with the mods!

**Comment by AlphaT3ch** [comment]
When does it get lifted? @mappum

**Comment by nicola** [comment]
should we just parse the page instead of using apis?

**Comment by Blecki** [comment]
We should start by getting the proper auth tokens to expand the limit, if @mappum hasn't already. Then we should switch to hooks.

**Comment by dos1** [comment]
We has hooks now. We close issue now?

**Comment by dos1** [comment]
Please close old issues.

**Comment by avdg** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
Manually closing on behalf of myself.
