### ISSUE TITLE
Bot IP: 162.243.149.229

### ISSUE THREAD

**Issue by mappum** [botwillacceptanything/botwillacceptanything#55]
`162.243.149.229`

Just in case you want it to run a server of some sort... Note that the bot is not running with root, so you can't use port 80. This is a 1GB DigitalOcean VPS in SF.

**Comment by AlphaT3ch** [comment]
I've added these notes to the README.md in [my pull request](https://github.com/botwillacceptanything/botwillacceptanything/pull/88)

**Comment by dequis** [comment]
This is in the readme now, close?

**Comment by zztemp** [comment]
You should forward port 80 to another port so we can make a more "public" site.

**Comment by mappum** [comment]
@zztemp Agreed. I'll set that up.

**Comment by timjrobinson** [comment]
Looks like the bot is down? http://162.243.149.229:3000/ doesn't work for me.

**Comment by avdg** [comment]
@timjrobinson I guess the bot is down: https://github.com/botwillacceptanything?tab=activity

**Comment by uptownhr** [comment]
can we close this issue?

**Comment by avdg** [comment]
"uptownhr +1
