### ISSUE TITLE
This repository needs a real software license

### ISSUE THREAD

**Issue by rspeer** [botwillacceptanything/botwillacceptanything#76]
The "Autonomous Software License" in the README is, for one thing, nonsense, but it also doesn't do the single thing that's important about an open-source license, which is to give people permission to copy, revise, and reuse the code.

I suggest using the MIT license.

**Comment by aetherwu** [comment]
I think it makes sense at all. I think there is no business about your human or 'open source movement'. It is all about the robot in itself. It doesn't care your human or  license.

**Comment by rspeer** [comment]
The fact that you want to anthropomorphize a repository is a terrible excuse for [license proliferation](http://en.wikipedia.org/wiki/License_proliferation).

Look, I'm not a lawyer, but what's even the point of a license if you're going to claim that this thing doesn't obey human laws, but obeys made-up robot laws instead? If you're claiming the legal system doesn't apply, *why write anything in legalese*?

A software license consisting of the words "LOL BUTTS" would be just as useful and give just as much permission for people to use the code.

The actual concern here is that someone might commit some code to this project one day that someone actually finds interesting and useful, and they won't be able to use it in a real project with a real license.

**Comment by rspeer** [comment]
Reasonably closed by #80.

**Comment by mwerner** [comment]
lol butts
